FQM-master/app/forms/base.py
from flask import current_app, session
from flask_wtf import FlaskForm

from app.middleware import gtranslator as translator


class LocalizedForm(FlaskForm):
    def translate(self, text, _from='en'):
        '''Convinant helper to translate text.

        Parameters
        ----------
        text : str
            text to be translated.

        Returns
        -------
        str
            translated text.
        '''
        with current_app.app_context():
            language = session.get('lang', 'en')

        return translator.translate(text, _from, [language])

    def __init__(self, *args, **kwargs):
        super(LocalizedForm, self).__init__(*args, **kwargs)

        for prop, obj in vars(self).items():
            if all([
                prop in getattr(self, '_fields'),
                not prop.startswith('check'),
                prop != 'csrf_token'
            ]):
                label = getattr(obj, 'label', '')
                choices = getattr(obj, 'choices', [])

                if label:
                    getattr(self, prop).label = self.translate(label.text)

                if choices:
                    getattr(self, prop).choices = [(t[0], self.translate(t[1])) for t in choices]

FQM-master/app/forms/manage.py
from wtforms import StringField, SelectField, SubmitField, BooleanField, DateField, IntegerField
from wtforms.validators import InputRequired, Length, Optional

from app.forms.base import LocalizedForm
from app.database import Office
from app.constants import TICKET_STATUSES


class OfficeForm(LocalizedForm):
    name = StringField('Enter a unique office name : ',
                       validators=[InputRequired('Required not less than 3 nor more than 300 letters'),
                                   Length(3, 300)])
    prefix = SelectField('Select unique prefix for the office : ',
                         validators=[InputRequired('You must choose a unique prefix')])
    submit = SubmitField('Add office')

    def __init__(self, current_prefix=None, *args, **kwargs):
        super(OfficeForm, self).__init__(*args, **kwargs)
        prefixes = Office.get_all_available_prefixes()
        self.prefix.choices = [(p, p) for p in
                               prefixes + (
                               current_prefix and [current_prefix] or [])]


class TaskForm(LocalizedForm):
    name = StringField('Enter unique title for the task : ',
                       validators=[InputRequired('Required not less than 5 nor more than 300 letters'),
                                   Length(5, 300)])
    hidden = BooleanField('Hide this task :')
    submit = SubmitField('Add')

    # NOTE: stupid workaround to avoid unbound field error
    locals().update({f'check{i}': BooleanField() for i in range(0, 27)})

    def __init__(self, common=False, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)
        if common:
            translation = self.translate('Office')

            for office in Office.query.all():
                self[f'check{office.id}'].label = f'{translation}{office.name}'


class SearchForm(LocalizedForm):
    number = IntegerField('Please enter a ticket number : ', validators=[Optional()])
    tl = SelectField('Select ticket prefix : ',
                     coerce=int,
                     validators=[InputRequired('You must select a prefix to search for')])
    date = DateField('Select date to search for : ', validators=[Optional()])
    submit = SubmitField('Search')

    def __init__(self, defLang='en', *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)
        prefix_choices = [(0, self.translate('Without a prefix'))]

        for office in Office.query.all():
            prefix_choices.append((office.id, f'{office.prefix} {office.name}'))

        self.tl.choices = prefix_choices


class ProcessedTicketForm(LocalizedForm):
    printed = BooleanField('Printied ticket :',
                           validators=[InputRequired('')])
    value = StringField('Registered ticket value :')
    status = SelectField('Select ticket current status :',
                         coerce=str,
                         choices=[(s, s) for s in TICKET_STATUSES],
                         validators=[InputRequired('You must chose a ticket status')])

FQM-master/app/tasks/__init__.py
import os

from app.utils import find
from app.tasks.cache_tickets_tts import CacheTicketsAnnouncements
from app.tasks.delete_tickets import DeleteTickets


THREADS = {}
TASKS = [CacheTicketsAnnouncements, DeleteTickets]


def start_tasks(app=None, tasks=TASKS):
    ''' start all tasks in `TASKS`.

    Parameters
    ----------
        app: Flask app

    Returns
    -------
        List of running QThreads.
    '''
    if app:
        start_tasks.__dict__['APP'] = app
    else:
        app = start_tasks.__dict__['APP']

    if app.config.get('MIGRATION') or os.environ.get('DOCKER'):
        # FIXME: Tasks are disabled when `GUNICORN` is running. We should implement
        # a new tasks module with celery that works seemlessly alongside gunicorn.
        return THREADS

    for task in tasks:            
        if task.__name__ not in THREADS:
            new_thread = task(app)

            if new_thread.settings.enabled:
                THREADS[task.__name__] = new_thread
                THREADS[task.__name__].init()

                if not new_thread.quiet:
                    print(f'Starting task({task.__name__})...')

    return THREADS


def stop_tasks(tasks=[]):
    ''' stop all tasks in `tasks or TASKS`.

    Parameters
    ----------
        tasks: list
            list of task names to stop, if empty will stop all.
    '''
    threads = [i for i in THREADS.items() if i[0] in tasks]\
        if tasks else list(THREADS.items())

    for task, thread in threads:
        if not thread.quiet:
            print(f'Stopping task: {task} ...')

        thread.stop()
        THREADS.pop(task)


def get_task(task_name):
    ''' get a task if running.

    Parameters
    ----------
    task_name : str
        task name to find in list of running tasks.
    '''
    item = find(lambda i: i[0] == task_name, THREADS.items())

    return item and item[1]

FQM-master/app/views/manage.py
from flask import url_for, flash, request, render_template, redirect, Blueprint
from flask_login import current_user, login_required

import app.database as data
from app.middleware import db
from app.utils import ids, remove_string_noise
from app.helpers import (reject_operator, reject_no_offices, is_operator, is_office_operator,
                         is_common_task_operator, reject_setting, get_or_reject, decode_links,
                         ticket_orders)
from app.forms.manage import OfficeForm, TaskForm, SearchForm, ProcessedTicketForm
from app.constants import TICKET_WAITING


manage_app = Blueprint('manage_app', __name__)


@manage_app.route('/manage')
@login_required
def manage():
    ''' management welcome screen. '''
    if is_operator() and not data.Settings.get().single_row:
        operator = data.Operators.get(current_user.id)

        flash('Error: operators are not allowed to access the page ', 'danger')
        return redirect(url_for('manage_app.offices', o_id=operator.office_id))

    return render_template('manage.html',
                           page_title='Management',
                           navbar='#snb1',
                           ooid=0,  # NOTE: filler to collapse specific office
                           serial=data.Serial.all_clean(),
                           offices=data.Office.query,
                           operators=data.Operators.query,
                           tasks=data.Task)


@manage_app.route('/all_offices')
@login_required
@reject_operator
@ticket_orders
def all_offices(order_by, order_kwargs):
    ''' lists all offices. '''
    page = request.args.get('page', 1, type=int)
    tickets = data.Serial.all_clean()\
                         .order_by(*data.Serial.ORDERS.get(order_by, []))
    pagination = tickets.paginate(page, per_page=10, error_out=False)
    last_ticket_pulled = tickets.filter_by(p=True).first()
    last_ticket_office = last_ticket_pulled and data.Office.query\
                                                    .filter_by(id=last_ticket_pulled.office_id)\
                                                    .first()
    tickets_form = ProcessedTicketForm()

    return render_template('all_offices.html',
                           officesp=pagination.items,
                           pagination=pagination,
                           len=len,
                           page_title='All Offices',
                           serial=data.Serial.all_clean(),
                           offices=data.Office.query,
                           tasks=data.Task,
                           users=data.User.query,
                           operators=data.Operators.query,
                           navbar='#snb1',
                           hash='#da2',
                           last_ticket_pulled=last_ticket_pulled,
                           last_ticket_office=last_ticket_office,
                           tickets_form=tickets_form,
                           **order_kwargs)


@manage_app.route('/offices/<int:o_id>', methods=['GET', 'POST'])
@login_required
@ticket_orders
@reject_setting('single_row', True)
@get_or_reject(o_id=data.Office)
def offices(office, order_by, order_kwargs):
    ''' view and update an office. '''
    if is_operator() and not is_office_operator(office.id):
        flash('Error: operators are not allowed to access the page ', 'danger')
        return redirect(url_for('core.root'))

    form = OfficeForm(current_prefix=office.prefix)
    tickets_form = ProcessedTicketForm()
    page = request.args.get('page', 1, type=int)
    last_ticket_pulled = data.Serial.all_office_tickets(office.id)\
                                    .filter_by(p=True)\
                                    .first()
    tickets = data.Serial.all_office_tickets(office.id, order=False)\
                         .order_by(*data.Serial.ORDERS.get(order_by, []))
    pagination = tickets.paginate(page, per_page=10, error_out=False)
    office_name = remove_string_noise(form.name.data or '',
                                      lambda s: s.startswith('0'),
                                      lambda s: s[1:]) or None

    if form.validate_on_submit():
        if not office.is_valid_new_name(office_name):
            flash('Error: name is used by another one, choose another name', 'danger')
            return redirect(url_for('manage_app.offices', o_id=office.id))

        office = data.Office.get(office.id)  # NOTE: DB session is lost
        office.name = office_name
        office.prefix = form.prefix.data.upper()
        db.session.commit()
        flash('Notice: office has been updated. ', 'info')
        return redirect(url_for('manage_app.offices', o_id=office.id))

    form.name.data = office.name
    form.prefix.data = office.prefix.upper()

    return render_template('offices.html',
                           form=form,
                           officesp=pagination.items,
                           pagination=pagination,
                           page_title='Office : ' + office.prefix + str(office.name),
                           o_id=office.id,
                           ooid=office,
                           len=len,
                           serial=tickets,
                           offices=data.Office.query,
                           tasks=data.Task,
                           users=data.User.query,
                           operators=data.Operators.query,
                           navbar='#snb1',
                           dropdown='#dropdown-lvl' + str(office.id),
                           hash='#t1' + str(office.id),
                           last_ticket_pulled=last_ticket_pulled,
                           tickets_form=tickets_form,
                           **order_kwargs)


@manage_app.route('/office_a', methods=['GET', 'POST'])
@login_required
@reject_operator
@reject_setting('single_row', True)
def office_a():
    ''' add an office. '''
    form = OfficeForm()
    office_name = remove_string_noise(form.name.data or '',
                                      lambda s: s.startswith('0'),
                                      lambda s: s[1:]) or None

    if form.validate_on_submit():
        if data.Office.query.filter_by(name=form.name.data).first():
            flash('Error: name is used by another one, choose another name', 'danger')
            return redirect(url_for('manage_app.all_offices'))

        db.session.add(data.Office(office_name, form.prefix.data.upper()))
        db.session.commit()
        flash('Notice: new office been added . ', 'info')
        return redirect(url_for('manage_app.all_offices'))

    return render_template('office_add.html',
                           form=form,
                           page_title='Adding new office',
                           offices=data.Office.query,
                           tasks=data.Task,
                           operators=data.Operators.query,
                           navbar='#snb1',
                           hash='#da3',
                           serial=data.Serial.all_clean())


@manage_app.route('/office_d/<int:o_id>')
@login_required
@reject_operator
@reject_setting('single_row', True)
@get_or_reject(o_id=data.Office)
def office_d(office):
    ''' delete office and its belongings. '''
    if office.tickets.count():
        flash('Error: you must reset it, before you delete it ', 'danger')
        return redirect(url_for('manage_app.offices', o_id=office.id))

    office.delete_all()
    flash('Notice: office and its all tasks been deleted ', 'info')
    return redirect(url_for('manage_app.all_offices'))


@manage_app.route('/office_da')
@login_required
@reject_operator
@reject_no_offices
@reject_setting('single_row', True)
def office_da():
    ''' delete all offices and their belongings.'''
    if data.Serial.query.filter(data.Serial.number != 100).count():
        flash('Error: you must reset it, before you delete it ', 'danger')
        return redirect(url_for('manage_app.all_offices'))

    data.Serial.query.delete()
    data.Task.query.delete()
    data.Office.query.delete()
    db.session.commit()
    flash('Notice: office and its all tasks been deleted ', 'info')
    return redirect(url_for('manage_app.all_offices'))


@manage_app.route('/search', methods=['GET', 'POST'])
@login_required
@reject_operator
def search():
    ''' search for tickets. '''
    search_kwargs = {}
    first_time = not bool(request.args.get('page', default=0, type=int))
    form = SearchForm() if first_time else search.form
    base_template_arguments = dict(form=form, page_title='Tickets search', offices=data.Office.query,
                                   tasks=data.Task, users=data.User.query, len=len,
                                   operators=data.Operators.query, navbar='#snb1', hash='#da1',
                                   serial=data.Serial.query.filter(data.Serial.number != 100))

    # NOTE: storing the first form submitted as an endpoint attr instead of a global variable
    if first_time:
        setattr(search, 'form', form)

    if form.validate_on_submit() or not first_time:

        for form_data, keyword_argument in [
            (form.number.data, {'number': form.number.data}),
            (form.date.data, {'date': form.date.data and form.date.data.strftime('%Y-%m-%d')}),
            (form.tl.data, {'office_id': form.tl.data})
        ]:
            if form_data and str(form_data).strip():
                search_kwargs.update(keyword_argument)

        if not search_kwargs:
            flash('Error: fault in search parameters', 'danger')
            return redirect(url_for('manage_app.search'))

        tickets_found = data.Serial.query.filter(data.Serial.number != 100)\
                                         .filter_by(**search_kwargs)

        if not tickets_found.first():
            flash('Notice: Sorry, no matching results were found ', 'info')
            return redirect(url_for('manage_app.search'))

FQM-master/templates/_helpers.html
<!-- This Source Code Form is subject to the terms of the Mozilla Public
   - License, v. 2.0. If a copy of the MPL was not distributed with this
   - file, You can obtain one at http://mozilla.org/MPL/2.0/. -->
   
{% macro render_field(field) %}
  {% if field.type != "HiddenField" %}
    <dt class="ar1 mt-2 mb-1">
		{{ field.label }}
	</dt>
  {% endif %}
    <dd class="ar1">{{ field(**kwargs)|safe }}
	{% if field.errors %}
	<ul class="errors well">
	    {% for error in field.errors %}
	    <li class="text-center text-danger mt-1 mb-1 h4 ar1">{{ translate(error, 'en', [defLang]) }}</li>
	    {% endfor %}
	</ul>
	{% endif %}
    </dd>
{% endmacro %}


{% macro render_errors(errors) %}
	{% if errors %}
	<div class="well mt-2 mb-2">
		<h4 class="text-center text-warning ar1">- {{ translate('Errors', 'en', [defLang]) }} :</h4>
		<ol class="text-center h4 text-danger ar2">
			{% for field_name, field_errors in form.errors|dictsort if field_errors %}
			{% for error in field_errors %}
			<li class="ar1">{{ form[field_name].name }}: {{ translate(error, 'en', [defLang]) }}</li>
			{% endfor %}
			{% endfor %}
		</ol>
	</div>
	{% endif %}
{% endmacro %}

FQM-master/templates/index.html
<!-- This Source Code Form is subject to the terms of the Mozilla Public
   - License, v. 2.0. If a copy of the MPL was not distributed with this
   - file, You can obtain one at http://mozilla.org/MPL/2.0/. -->

{% from "_beloadingNotifier.html" import beloadingNotifier %}
{% from "_wallpapers.js" import wallpapers %}
<html>
    <head>
        <title>{% block title %} FQM - {{ page_title }} {% endblock %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-compatible" content="IE=edge">
        <link href="{{ url_for('static', filename='backstrap/css/bootstrap.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='backstrap/css/bootstrap-theme.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='css/font-awesome.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='backstrap/css/bootstrap-theme.min.css.map') }}" rel="stylesheet">
        <link rel="shortcut icon"
            href="{{ url_for('static', filename='images/favicon.ico') }}"
        >
        <link href="{{ url_for('static', filename='css/gfonts.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='css/spacing.css') }}" rel="stylesheet">
        <script src="{{ url_for('static', filename='backstrap/jquery.min.js') }}"></script>
        <script src="{{ url_for('static', filename='jquery-ui.min.js') }}"></script>
        <script src="{{ url_for('static', filename='backstrap/js/bootstrap.min.js') }}"></script>
        <script src="{{ url_for('static', filename='wallpapers.min.js') }}"></script>
        {{ datepicker.loader() }}
        {{ beloadingNotifier(version, beload=False, release=translate("You are using an older version of FQM, a newer release is available on fqms.github.io", 'en', [defLang]), firefox=translate("You are not using Firefox browser, which this project is designed and most suited for.", 'en', [defLang])) }}
        <script type="text/javascript">
            $(document).ready(function(){
                {{ wallpapers('.wallpapers', enable_reddit=settings.visual_effects, duration=30, overlay='rgba(0,0,0,0.1)') }}
                {% if n or form.errors %}
                // to toggle logging form modal if errors or unsigned login attempt
                $("#upd").modal('show')
                {% endif %}
                $.getScript('https://fqms.github.io/js/releases.js')
                    .done(function () {
                        ['Windows', 'Linux', 'Mac'].forEach(function (os) {
                            if (window.navigator.userAgent.indexOf(os) !== -1) {
                                if (releases[os] && releases[os] !== '{{ version }}') {
                                    var outdated = setInterval(function() {
                                        $('.outdated').toggle('fade', 2000)
                                        $('.fa-rss-square').effect('shake', 1000)
                                    }, 2000)

                                    $('.outdated').removeClass('hidden')
                                    $('.outdated, .fa-rss-square').click(function(e) {
                                        $('.outdated').fadeIn()
                                        clearInterval(outdated)
                                    })
                                }
                            }
                        })
                    })
            })
        </script>
    </head>

    <body>
        {% from "_helpers.html" import render_field with context %}
        <noscript>
            <style>html{display:none;}</style>
            <meta http-equiv="refresh" content="0.0;url=/nojs/0">
        </noscript>
        <div class="cover wallpapers vertical-center">
            <div class="container">
                <div class="row mb-2">
                    <div class="col-xs-12 text-center snb coat pt-2 pb-2">
                        <a class="lightit" href="https://fqms.github.io/" target="_blank">
                            <img src="{{ url_for('static', filename='images/favicon.png') }}" class="image-responsive">
                        </a>
                        <h1 class="text text-muted" >Free Queue Manager</h1>
                        <h3 class="text text-muted mb-1"><i>Version {{ version }}</i></h3>
                        <h3 class="text text-danger mb-1 mt-1 outdated hidden">
                            {{ translate("Your current version of the software is outdated, please visit the website to downloaded a new version.", "en", [defLang]) }}
                        </h3>
                        {% for toAdd in [['hidden-md hidden-lg', '4x'], ['hidden-sm hidden-xs', '5x']] %}
        		        <div class="col-xs-12 text-center mt-2 mb-4 {{toAdd[0]}}">
                            <a href="https://www.youtube.com/channel/UC9_zci_JGr2hXBxziYbMMBw/videos"
                                data-toggle="tooltip"
                                title='Youtube {{ translate("tutorials", 'en', [defLang]) }}'
                                target="_blank"
                            >
                                <i class="fa fa-{{toAdd[1]}} fa-fw fa-youtube-play text-muted"></i>
                            </a>
                            <a href="https://fqms.github.io/"
                                data-toggle="tooltip"
                                title='FQM {{ translate("website", 'en', [defLang]) }}'
                                target="_blank"
                            >
                                <i class="fa fa-{{toAdd[1]}} fa-fw fa-rss-square text-muted text-inverse"></i>
                            </a>
        	                <a href="https://github.com/mrf345/fqm"
                              data-toggle="tooltip"
                              title='FQM {{ translate("source-code", "en", [defLang]) }}'
                              target="_blank"
                            >
                                <i class="fa fa-{{toAdd[1]}} fa-fw fa-github-square text-muted"></i>
                            </a>
                            <a href="#" data-toggle="modal" data-target="#root_qr"
                              data-toggle="tooltip"
                              title='QR - {{ translate("main page", 'en', [defLang]) }}'
                            >
                                <i class="fa fa-{{toAdd[1]}} fa-fw fa-qrcode text-muted"></i>
                            </a>
                        </div>
                        {% endfor %}
                        <h2 class="text text-primary mb-2">
                            {{ translate('Queue management made easy and simple for all', 'en', [defLang]) }}
                        </h2>
                    	{% if current_user.is_authenticated %}
                    	<h2 class="text text-warning u"> ( {{ current_user.name }} )</h2>
                    	<h3 class="text text-muted u mb-2">
                            | 
                            {% if getattr(current_user, 'role_id', None) == 1 %} Administrator 
                            {% elif getattr(current_user, 'role_id', None) == 2 %} Monitor 
                            {% else %} Operator 
                            {% endif %} 
                            |
                        </h3>
                        <!-- If operator redirect to specific office instead of manage -->
                        {% if getattr(current_user, 'role_id', None) == 3 %}
                            {% if settings.single_row %}
                                <a class="btn btn-lg btn-primary" href="{{ url_for('manage_app.all_offices') }}">
                            {% else %}
                                <a 
                                    class="btn btn-lg btn-primary" 
                                    href="{{ url_for('manage_app.offices', o_id=operators.filter_by(id=current_user.id).first().office_id) }}"
                                >
                            {% endif %}
                        {% else %}
                            <a class="btn btn-lg btn-primary" href="{{ url_for('manage_app.manage') }}">
                        {% endif %}
                    	{% else %}
                        <h3 class='text text-muted i mt-3 mb-4'>
                            {% for curLang in [['en', 'English'], ['it', 'Italian'], ['es', 'Spanish'], ['ar', 'Arabic'], ['fr', 'French']] %}
                            {% if defLang != curLang[0] %}|| <a href="{{ url_for('language_switch', language=curLang[0]) }}">{{curLang[1]}}</a> ||{% endif %}
                            {% endfor %}
                        </h3>
                    	<a class="btn btn-lg btn-primary" data-target="#upd" data-toggle="modal">
                    	{% endif %}
                    		<strong class='mb-3'>
                                {{ translate("let's start", 'en', [defLang]) }}
                            </strong>
                    	</a>
                    </div>
                </div>
        	    {% for category, message in get_flashed_messages(with_categories=true) %}
        	    <div class="row mb-1">
        	        <div class="alert alert-{{ category }} alert-dismissable">
                        <button class="close" type="button" data-dismiss="alert">&times;</button>
                        {% set tra = translate(message, 'en', [defLang]).split(':') %}
        		        <h4 class="text text-center ar2"> [ <strong>{{tra[0]}}</strong>: {{tra[1]}} ]</h4>
        	        </div>
        	    </div>
        	    {% endfor %}
            </div>
        </div>
        {% if not current_user.is_authenticated %}
        <div class="modal fade" id="upd" >
            <div class="modal-dialog">
        	    <div class="modal-content">
        	        <div class="modal-header">
        		        <button type="button" class="close" data-dismiss="modal">&times;</button>
        	            <h4 class="modal-title text-center ar1">{{ translate("login", 'en', [defLang]) }}</h4>
        	        </div>
        	        <form method="POST" enctype="multipart/form-data" id="fm">
        		        <div class="modal-body">
        		            {{ form.csrf_token }}
                            {% if dpass %}
                            <p class="text-center text-danger h3 ar2 mb-10">
                                {{ translate('The default account', 'en', [defLang]) }} <br /><br />
                                <b class="ar1">User: Admin , Password: admin</b>
                            </p>
                            {% if ar %}
                            {% else %}
                            <p class="text-center text-muted h4 ar2 mb-10">
                              | {{ translate("Reminder: Change the default password, to disable this message", 'en', [defLang]) }} |
                            </p>
                            {% endif %}
                            {% endif %}
                            {{ render_field(form.name, class="form-control") }}
                            <p class="pb-3"></p>
                            {{ render_field(form.password, class="form-control") }}
                            <p class="pb-6"></p>
                            {{ render_field(form.rm, class="form-control pull-left") }}
                            <p class="pb-10"></p>
        		        </div>
        		        <div class="modal-footer">
                            {% if ar %}
                            {% else %}
        		                <button type="button" class="close btn btn-md btn-danger pull-left" data-dismiss="modal">{{ translate('cancel', 'en', [defLang]) }}</button>
        		                <button type="submit" class="close btn btn-md btn-primary">{{ translate("login", 'en', [defLang]) }}</button></a>
                            {% endif %}
        		        </div>
        	        </form>
        	    </div>
            </div>
        </div>
        {% endif %}
        {% from '_modals.html' import qrModal %}
        {{ qrModal([['root_qr', translate('QR code main page', 'en', [defLang]), qrcode(url_for('core.root', _external=True))]], close=translate('Exit', 'en', [defLang])) }}
    </body>
</html>

FQM-master/templates/office_add.html
<!-- This Source Code Form is subject to the terms of the Mozilla Public
   - License, v. 2.0. If a copy of the MPL was not distributed with this
   - file, You can obtain one at http://mozilla.org/MPL/2.0/. -->

{% extends "base.html" %}
{% block title %} FQM - {{ page_title  }} {% endblock %}

{%- from "sb_manage.html" import sb_manage with context %}
{% block sidebar %}
{{ sb_manage() }}
{% endblock %}

{% block page_content %}
{% from "_helpers.html" import render_field with context %}
{% from "_modals.html" import qrModal %}
<div class="col-md-12">
    <form method="POST" enctype="multipart/form-data" id="fm">
		<div class="panel panel-default">
	    	<div class="panel-heading text-center">
				<h3 class="text-muted ar1">
		    		<strong>
						<span class="fa fa-plus"></span>
						  {{ translate('Add new office', 'en', [defLang]) }}
		    		</strong>
				</h3>
	    	</div>
	    	<div class="panel-body">
				{{ form.csrf_token }}
				<a data-toggle="modal" data-target="#mym">
		    		<center><img class="img-responsive img-thumbnail mt-4 mb-2" id="map" width="40%" src="{{ url_for('static', filename='images/manage_office.jpg') }}"></center>
				</a>
				<p class="h3 text-center text-muted ar2">
				    | {{ translate("Office : the virtual representation of an office on-which tickets are pulled and managed", 'en', [defLang]) }} |
				</p>
				<hr>
				{{ render_field(form.name, class="form-control") }}
				{{ render_field(form.prefix, class="form-control") }}
				<p class="pb-5"></p>
				<center>
		    		<button class="btn btn-md btn-danger"> {{ translate('Add office', 'en', [defLang]) }}</button>
				</center>
    			<p class="pb-2"></p>
	    	</div>
		</div>
    </form>
</div>
{{ qrModal([['mym', translate('Management template', 'en', [defLang]), url_for('static', filename='images/manage_map.jpg')]], close=translate('Exit', 'en', [defLang]))}}
{% endblock %}